name: Test Homework
on:
  push:
    branches: [ "main" ]
permissions:
   contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
           python -m pip install --upgrade pip
           pip install flake8 pytest
           pip install pandas
           if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Run and Test
        run: |
          python ./Homework/HW1/script.py -g all
          python ./Homework/HW2/script.py -g all
          python ./Homework/HW3/script.py -g all
          python ./Homework/HW4/script.py -g all
          python ./Homework/HW5/script.py -g all


      - name: Report
        run: |
          echo "🧞‍♂️Job Status: ${{ job.status }}."
